@Practice.Api_HostAddress = https://localhost:7136

###

GET {{Practice.Api_HostAddress}}/api/items

###
GET {{Practice.Api_HostAddress}}/api/ping

POST {{Practice.Api_HostAddress}}/api/items
Content-Type: application/json

{
  //CreateItemRequest
}

###
